/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */
package com.paxxis.cornerstone.json.parser;

public interface JSONParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int DOUBLEQUOTE = 2;
  int LBRACE = 3;
  int RBRACE = 4;
  int LBRACKET = 5;
  int RBRACKET = 6;
  int PLUS = 7;
  int MINUS = 8;
  int COMMA = 9;
  int TRUE = 10;
  int FALSE = 11;
  int NULL = 12;
  int VALUESEP = 13;
  int INTEGERLITERAL = 14;
  int EXP = 15;
  int FLOATLITERAL = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "<TRUE>",
    "<FALSE>",
    "<NULL>",
    "\":\"",
    "<INTEGERLITERAL>",
    "<EXP>",
    "<FLOATLITERAL>",
  };

}
