/* Generated By:JavaCC: Do not edit this line. CALRuleParserConstants.java */
package com.paxxis.chime.cal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CALRuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int SINGLEQUOTE = 7;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int LBRACKET = 13;
  /** RegularExpression Id. */
  int RBRACKET = 14;
  /** RegularExpression Id. */
  int ASSIGNMENT = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int MULT = 18;
  /** RegularExpression Id. */
  int DIV = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int NOTEQUALS = 22;
  /** RegularExpression Id. */
  int STREQUALS = 23;
  /** RegularExpression Id. */
  int STRCAT = 24;
  /** RegularExpression Id. */
  int GREATERTHAN = 25;
  /** RegularExpression Id. */
  int LESSTHAN = 26;
  /** RegularExpression Id. */
  int GREATERTHANEQ = 27;
  /** RegularExpression Id. */
  int LESSTHANEQ = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int WHEN = 30;
  /** RegularExpression Id. */
  int SET = 31;
  /** RegularExpression Id. */
  int TO = 32;
  /** RegularExpression Id. */
  int RULE = 33;
  /** RegularExpression Id. */
  int SWITCH = 34;
  /** RegularExpression Id. */
  int CASE = 35;
  /** RegularExpression Id. */
  int EVENT = 36;
  /** RegularExpression Id. */
  int TIMER = 37;
  /** RegularExpression Id. */
  int DEFCASE = 38;
  /** RegularExpression Id. */
  int CONDITION = 39;
  /** RegularExpression Id. */
  int CHANGES = 40;
  /** RegularExpression Id. */
  int RETURNS = 41;
  /** RegularExpression Id. */
  int RETURN = 42;
  /** RegularExpression Id. */
  int TRUE = 43;
  /** RegularExpression Id. */
  int FALSE = 44;
  /** RegularExpression Id. */
  int REFERENCE = 45;
  /** RegularExpression Id. */
  int VARIABLE = 46;
  /** RegularExpression Id. */
  int START = 47;
  /** RegularExpression Id. */
  int SUBMIT = 48;
  /** RegularExpression Id. */
  int DURABLE = 49;
  /** RegularExpression Id. */
  int DYNAMIC = 50;
  /** RegularExpression Id. */
  int AS = 51;
  /** RegularExpression Id. */
  int ON = 52;
  /** RegularExpression Id. */
  int IF = 53;
  /** RegularExpression Id. */
  int ELSE = 54;
  /** RegularExpression Id. */
  int ELSEIF = 55;
  /** RegularExpression Id. */
  int WHILE = 56;
  /** RegularExpression Id. */
  int BREAK = 57;
  /** RegularExpression Id. */
  int ERROR = 58;
  /** RegularExpression Id. */
  int METHODSEP = 59;
  /** RegularExpression Id. */
  int VALUESEP = 60;
  /** RegularExpression Id. */
  int IS = 61;
  /** RegularExpression Id. */
  int AND = 62;
  /** RegularExpression Id. */
  int OR = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int WAIT = 65;
  /** RegularExpression Id. */
  int UNTIL = 66;
  /** RegularExpression Id. */
  int ARRAY = 67;
  /** RegularExpression Id. */
  int TABLE = 68;
  /** RegularExpression Id. */
  int INTEGER = 69;
  /** RegularExpression Id. */
  int DOUBLE = 70;
  /** RegularExpression Id. */
  int BOOLEAN = 71;
  /** RegularExpression Id. */
  int STRING = 72;
  /** RegularExpression Id. */
  int DATE = 73;
  /** RegularExpression Id. */
  int STOCKSYMBOL = 74;
  /** RegularExpression Id. */
  int DATAINSTANCE = 75;
  /** RegularExpression Id. */
  int SHAPE = 76;
  /** RegularExpression Id. */
  int EXTENSION = 77;
  /** RegularExpression Id. */
  int QUERY = 78;
  /** RegularExpression Id. */
  int NARROW = 79;
  /** RegularExpression Id. */
  int WHERE = 80;
  /** RegularExpression Id. */
  int RATING = 81;
  /** RegularExpression Id. */
  int FIELD = 82;
  /** RegularExpression Id. */
  int PRINT = 83;
  /** RegularExpression Id. */
  int NEWLINE = 84;
  /** RegularExpression Id. */
  int name = 85;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 86;
  /** RegularExpression Id. */
  int DATELITERAL = 87;
  /** RegularExpression Id. */
  int FLOATLITERAL = 88;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 6>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"==\"",
    "\"!=\"",
    "<STREQUALS>",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<DO>",
    "<WHEN>",
    "<SET>",
    "<TO>",
    "<RULE>",
    "<SWITCH>",
    "<CASE>",
    "<EVENT>",
    "<TIMER>",
    "<DEFCASE>",
    "<CONDITION>",
    "<CHANGES>",
    "<RETURNS>",
    "<RETURN>",
    "<TRUE>",
    "<FALSE>",
    "\"Reference\"",
    "<VARIABLE>",
    "<START>",
    "<SUBMIT>",
    "<DURABLE>",
    "<DYNAMIC>",
    "<AS>",
    "<ON>",
    "<IF>",
    "<ELSE>",
    "<ELSEIF>",
    "<WHILE>",
    "<BREAK>",
    "<ERROR>",
    "\":\"",
    "\"::\"",
    "<IS>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<WAIT>",
    "<UNTIL>",
    "\"Array\"",
    "\"Table\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Boolean\"",
    "\"String\"",
    "\"Date\"",
    "\"StockSymbol\"",
    "\"DataInstance\"",
    "\"Shape\"",
    "\"Extension\"",
    "\"Query\"",
    "<NARROW>",
    "<WHERE>",
    "<RATING>",
    "<FIELD>",
    "<PRINT>",
    "\"newLine\"",
    "<name>",
    "<INTEGERLITERAL>",
    "<DATELITERAL>",
    "<FLOATLITERAL>",
    "\";\"",
  };

}
