/* Generated By:JavaCC: Do not edit this line. CALRuleParserTokenManager.java */
package com.paxxis.chime.cal.parser;
import java.io.*;
import java.util.*;
import com.paxxis.chime.client.common.cal.*;

/** Token Manager. */
public class CALRuleParserTokenManager implements CALRuleParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active1 & 0x4000L) != 0L)
         {
            jjmatchedKind = 85;
            return 48;
         }
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 85;
            return 273;
         }
         if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 85;
            return 207;
         }
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 85;
            return 333;
         }
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 85;
            return 25;
         }
         if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 85;
            return 76;
         }
         if ((active0 & 0x20000L) != 0L)
            return 364;
         if ((active1 & 0x100000L) != 0L)
         {
            jjmatchedKind = 85;
            return 337;
         }
         if ((active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 85;
            return 318;
         }
         if ((active1 & 0xa40L) != 0L)
         {
            jjmatchedKind = 85;
            return 94;
         }
         if ((active1 & 0x1500L) != 0L)
         {
            jjmatchedKind = 85;
            return 182;
         }
         return -1;
      case 1:
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x107ff8L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 1;
            return 48;
         }
         return -1;
      case 2:
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x107ff8L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 2;
            return 48;
         }
         return -1;
      case 3:
         if ((active1 & 0x200L) != 0L)
            return 48;
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x107df8L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 3;
            return 48;
         }
         return -1;
      case 4:
         if ((active1 & 0x5018L) != 0L)
            return 48;
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x102de0L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 4;
            return 48;
         }
         return -1;
      case 5:
         if ((active1 & 0x140L) != 0L)
            return 48;
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x102ca0L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 5;
            return 48;
         }
         return -1;
      case 6:
         if ((active1 & 0x1000a0L) != 0L)
            return 48;
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x2c00L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 6;
            return 48;
         }
         return -1;
      case 7:
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x2c00L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 7;
            return 48;
         }
         return -1;
      case 8:
         if ((active1 & 0xc00L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 8;
            return 48;
         }
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x2000L) != 0L)
            return 48;
         return -1;
      case 9:
         if ((active1 & 0xc00L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 9;
            return 48;
         }
         return -1;
      case 10:
         if ((active1 & 0x400L) != 0L)
            return 48;
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 10;
            return 48;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L);
      case 34:
         return jjStopAtPos(0, 8);
      case 39:
         return jjStopAtPos(0, 7);
      case 40:
         return jjStopAtPos(0, 11);
      case 41:
         return jjStopAtPos(0, 12);
      case 42:
         return jjStopAtPos(0, 18);
      case 43:
         return jjStopAtPos(0, 16);
      case 44:
         return jjStopAtPos(0, 20);
      case 45:
         return jjStartNfaWithStates_0(0, 17, 364);
      case 47:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_0(0xcL, 0x0L);
      case 58:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 59:
         return jjStopAtPos(0, 89);
      case 60:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x0L);
      case 61:
         jjmatchedKind = 15;
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
      case 62:
         jjmatchedKind = 25;
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xa40L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x200000000000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1500L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L);
      case 91:
         return jjStopAtPos(0, 13);
      case 93:
         return jjStopAtPos(0, 14);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000L);
      case 123:
         return jjStopAtPos(0, 9);
      case 124:
         return jjStopAtPos(0, 24);
      case 125:
         return jjStopAtPos(0, 10);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(1, 3);
         break;
      case 47:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      case 58:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         break;
      case 61:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         else if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(1, 22);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xa10L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0x100000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xc0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x500L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x480L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x108L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2a20L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x808L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400L);
      case 101:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 73, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L, active1, 0x2020L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x90L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800L);
      case 101:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 68, 48);
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 76, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x100000L);
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2100L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L, active1, 0L);
      case 121:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(4, 67, 48);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 78, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80L);
      case 101:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 70, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000L, active1, 0x20L);
      case 103:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 72, 48);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100800L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 101:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 84, 48);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000L);
      case 110:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 71, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000L, active1, 0L);
      case 114:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 48);
         break;
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800L);
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x2000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x800L);
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400L);
      case 101:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 45, 48);
         break;
      case 110:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(8, 77, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1);
      return 9;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa10_0(active1, 0x800L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1);
}
static private int jjMoveStringLiteralDfa10_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(8, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1);
      return 10;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa11_0(active1, 0x800L);
      case 108:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(10, 74, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1);
}
static private int jjMoveStringLiteralDfa11_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(9, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1);
      return 11;
   }
   switch(curChar)
   {
      case 101:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(11, 75, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 364;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 86)
                        kind = 86;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if ((0x401000000000L & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(352, 353);
                  break;
               case 333:
               case 48:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 76:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 207:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 337:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 273:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 94:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 364:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(353, 354);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 86)
                        kind = 86;
                     jjCheckNAdd(352);
                  }
                  break;
               case 318:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 182:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 25:
                  if ((0x83ff405000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 47:
                  if ((0x401000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 351:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(352, 353);
                  break;
               case 352:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 86)
                     kind = 86;
                  jjCheckNAdd(352);
                  break;
               case 353:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(353, 354);
                  break;
               case 354:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(355, 356);
                  break;
               case 355:
                  if (curChar == 45)
                     jjCheckNAdd(356);
                  break;
               case 356:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(356, 357);
                  break;
               case 357:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(358, 359);
                  break;
               case 358:
                  if (curChar == 45)
                     jjCheckNAdd(359);
                  break;
               case 359:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAdd(359);
                  break;
               case 360:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 86)
                     kind = 86;
                  jjCheckNAddStates(0, 4);
                  break;
               case 361:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(361, 362);
                  break;
               case 362:
                  if (curChar == 46)
                     jjCheckNAdd(363);
                  break;
               case 363:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  jjCheckNAdd(363);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 78)
                     jjAddStates(5, 6);
                  else if (curChar == 110)
                     jjAddStates(7, 8);
                  else if (curChar == 73)
                     jjAddStates(9, 10);
                  else if (curChar == 105)
                     jjAddStates(11, 12);
                  else if (curChar == 79)
                     jjAddStates(13, 14);
                  else if (curChar == 111)
                     jjAddStates(15, 16);
                  else if (curChar == 65)
                     jjAddStates(17, 19);
                  else if (curChar == 97)
                     jjAddStates(20, 22);
                  else if (curChar == 70)
                     jjAddStates(23, 24);
                  else if (curChar == 102)
                     jjAddStates(25, 26);
                  else if (curChar == 82)
                     jjAddStates(27, 31);
                  else if (curChar == 67)
                     jjAddStates(32, 34);
                  else if (curChar == 99)
                     jjAddStates(35, 37);
                  else if (curChar == 114)
                     jjAddStates(38, 41);
                  else if (curChar == 84)
                     jjAddStates(42, 44);
                  else if (curChar == 116)
                     jjAddStates(45, 47);
                  else if (curChar == 83)
                     jjAddStates(48, 51);
                  else if (curChar == 115)
                     jjAddStates(52, 55);
                  else if (curChar == 119)
                     jjAddStates(56, 59);
                  else if (curChar == 87)
                     jjAddStates(60, 63);
                  else if (curChar == 100)
                     jjAddStates(64, 67);
                  else if (curChar == 68)
                     jjAddStates(68, 71);
                  else if (curChar == 69)
                     jjAddStates(72, 76);
                  else if (curChar == 101)
                     jjAddStates(77, 81);
                  else if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 40;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 30;
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 333:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 83)
                  {
                     if (kind > 61)
                        kind = 61;
                  }
                  else if (curChar == 70)
                  {
                     if (kind > 53)
                        kind = 53;
                  }
                  break;
               case 76:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 91;
                  else if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 87;
                  else if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 79;
                  else if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 75;
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 207:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 213;
                  else if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 210;
                  else if (curChar == 79)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  break;
               case 337:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 341;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 273:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 291;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 286;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 275;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 272;
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 94:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 89)
                     jjstateSet[jjnewStateCnt++] = 111;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 105;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 99;
                  else if (curChar == 79)
                  {
                     if (kind > 29)
                        kind = 29;
                  }
                  break;
               case 318:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 321;
                  else if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 319;
                  else if (curChar == 83)
                  {
                     if (kind > 51)
                        kind = 51;
                  }
                  break;
               case 182:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 195;
                  else if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 190;
                  else if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 186;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 25:
                  if ((0x7fffffe97ffffffL & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAdd(48);
                  }
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 1:
                  if (curChar == 101 && kind > 46)
                     kind = 46;
                  break;
               case 2:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 69 && kind > 46)
                     kind = 46;
                  break;
               case 10:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 107 && kind > 57)
                     kind = 57;
                  break;
               case 18:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 75 && kind > 57)
                     kind = 57;
                  break;
               case 23:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 108 && kind > 66)
                     kind = 66;
                  break;
               case 28:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 76 && kind > 66)
                     kind = 66;
                  break;
               case 33:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 116 && kind > 83)
                     kind = 83;
                  break;
               case 38:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 84 && kind > 83)
                     kind = 83;
                  break;
               case 43:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if ((0x7fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 48:
                  if ((0x7fffffe97ffffffL & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(48);
                  break;
               case 49:
                  if (curChar == 101)
                     jjAddStates(77, 81);
                  break;
               case 50:
                  if (curChar == 115 && kind > 23)
                     kind = 23;
                  break;
               case 51:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 116 && kind > 36)
                     kind = 36;
                  break;
               case 56:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 101 && kind > 54)
                     kind = 54;
                  break;
               case 60:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 102 && kind > 55)
                     kind = 55;
                  break;
               case 63:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 114 && kind > 58)
                     kind = 58;
                  break;
               case 68:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 69)
                     jjAddStates(72, 76);
                  break;
               case 72:
                  if (curChar == 83 && kind > 23)
                     kind = 23;
                  break;
               case 73:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 77:
                  if (curChar == 84 && kind > 36)
                     kind = 36;
                  break;
               case 78:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 69 && kind > 54)
                     kind = 54;
                  break;
               case 82:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 70 && kind > 55)
                     kind = 55;
                  break;
               case 85:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 82 && kind > 58)
                     kind = 58;
                  break;
               case 90:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 68)
                     jjAddStates(68, 71);
                  break;
               case 95:
                  if (curChar == 84 && kind > 38)
                     kind = 38;
                  break;
               case 96:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 69 && kind > 49)
                     kind = 49;
                  break;
               case 102:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 67 && kind > 50)
                     kind = 50;
                  break;
               case 108:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 89)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 100)
                     jjAddStates(64, 67);
                  break;
               case 114:
                  if (curChar == 111 && kind > 29)
                     kind = 29;
                  break;
               case 115:
                  if (curChar == 116 && kind > 38)
                     kind = 38;
                  break;
               case 116:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 101 && kind > 49)
                     kind = 49;
                  break;
               case 122:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 99 && kind > 50)
                     kind = 50;
                  break;
               case 128:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 87)
                     jjAddStates(60, 63);
                  break;
               case 134:
                  if (curChar == 78 && kind > 30)
                     kind = 30;
                  break;
               case 135:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 69 && kind > 56)
                     kind = 56;
                  break;
               case 138:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 84 && kind > 65)
                     kind = 65;
                  break;
               case 142:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 69 && kind > 80)
                     kind = 80;
                  break;
               case 145:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 119)
                     jjAddStates(56, 59);
                  break;
               case 149:
                  if (curChar == 110 && kind > 30)
                     kind = 30;
                  break;
               case 150:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 101 && kind > 56)
                     kind = 56;
                  break;
               case 153:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 116 && kind > 65)
                     kind = 65;
                  break;
               case 157:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 101 && kind > 80)
                     kind = 80;
                  break;
               case 160:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 115)
                     jjAddStates(52, 55);
                  break;
               case 164:
                  if (curChar == 116 && kind > 31)
                     kind = 31;
                  break;
               case 165:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 104 && kind > 34)
                     kind = 34;
                  break;
               case 167:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 116 && kind > 47)
                     kind = 47;
                  break;
               case 172:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 116 && kind > 48)
                     kind = 48;
                  break;
               case 176:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 83)
                     jjAddStates(48, 51);
                  break;
               case 181:
                  if (curChar == 84 && kind > 31)
                     kind = 31;
                  break;
               case 183:
                  if (curChar == 72 && kind > 34)
                     kind = 34;
                  break;
               case 184:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 84 && kind > 47)
                     kind = 47;
                  break;
               case 189:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 84 && kind > 48)
                     kind = 48;
                  break;
               case 193:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 116)
                     jjAddStates(45, 47);
                  break;
               case 198:
                  if (curChar == 111 && kind > 32)
                     kind = 32;
                  break;
               case 199:
                  if (curChar == 114 && kind > 37)
                     kind = 37;
                  break;
               case 200:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 101 && kind > 43)
                     kind = 43;
                  break;
               case 204:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 84)
                     jjAddStates(42, 44);
                  break;
               case 208:
                  if (curChar == 82 && kind > 37)
                     kind = 37;
                  break;
               case 209:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 69 && kind > 43)
                     kind = 43;
                  break;
               case 213:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 114)
                     jjAddStates(38, 41);
                  break;
               case 216:
                  if (curChar == 101 && kind > 33)
                     kind = 33;
                  break;
               case 217:
               case 272:
                  if (curChar == 108)
                     jjCheckNAdd(216);
                  break;
               case 218:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 115 && kind > 41)
                     kind = 41;
                  break;
               case 220:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 110 && kind > 42)
                     kind = 42;
                  break;
               case 226:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 103 && kind > 81)
                     kind = 81;
                  break;
               case 231:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 99)
                     jjAddStates(35, 37);
                  break;
               case 236:
                  if (curChar == 101 && kind > 35)
                     kind = 35;
                  break;
               case 237:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 110 && kind > 39)
                     kind = 39;
                  break;
               case 240:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 115 && kind > 40)
                     kind = 40;
                  break;
               case 248:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 67)
                     jjAddStates(32, 34);
                  break;
               case 254:
                  if (curChar == 69 && kind > 35)
                     kind = 35;
                  break;
               case 255:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 78 && kind > 39)
                     kind = 39;
                  break;
               case 258:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 83 && kind > 40)
                     kind = 40;
                  break;
               case 266:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 82)
                     jjAddStates(27, 31);
                  break;
               case 274:
                  if (curChar == 69 && kind > 33)
                     kind = 33;
                  break;
               case 275:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 83 && kind > 41)
                     kind = 41;
                  break;
               case 278:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 78 && kind > 42)
                     kind = 42;
                  break;
               case 284:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 71 && kind > 81)
                     kind = 81;
                  break;
               case 289:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 290:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 291:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 293:
                  if (curChar == 102)
                     jjAddStates(25, 26);
                  break;
               case 294:
                  if (curChar == 101 && kind > 44)
                     kind = 44;
                  break;
               case 295:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 296:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 297:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 298:
                  if (curChar == 100 && kind > 82)
                     kind = 82;
                  break;
               case 299:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 300:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 301:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 302:
                  if (curChar == 70)
                     jjAddStates(23, 24);
                  break;
               case 303:
                  if (curChar == 69 && kind > 44)
                     kind = 44;
                  break;
               case 304:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 307:
                  if (curChar == 68 && kind > 82)
                     kind = 82;
                  break;
               case 308:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if (curChar == 97)
                     jjAddStates(20, 22);
                  break;
               case 312:
                  if (curChar == 115 && kind > 51)
                     kind = 51;
                  break;
               case 313:
                  if (curChar == 101 && kind > 61)
                     kind = 61;
                  break;
               case 314:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 315:
                  if (curChar == 100 && kind > 62)
                     kind = 62;
                  break;
               case 316:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 317:
                  if (curChar == 65)
                     jjAddStates(17, 19);
                  break;
               case 319:
                  if (curChar == 69 && kind > 61)
                     kind = 61;
                  break;
               case 320:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 68 && kind > 62)
                     kind = 62;
                  break;
               case 322:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 323:
                  if (curChar == 111)
                     jjAddStates(15, 16);
                  break;
               case 324:
                  if (curChar == 110 && kind > 52)
                     kind = 52;
                  break;
               case 325:
                  if (curChar == 114 && kind > 63)
                     kind = 63;
                  break;
               case 326:
                  if (curChar == 79)
                     jjAddStates(13, 14);
                  break;
               case 327:
                  if (curChar == 78 && kind > 52)
                     kind = 52;
                  break;
               case 328:
                  if (curChar == 82 && kind > 63)
                     kind = 63;
                  break;
               case 329:
                  if (curChar == 105)
                     jjAddStates(11, 12);
                  break;
               case 330:
                  if (curChar == 102 && kind > 53)
                     kind = 53;
                  break;
               case 331:
                  if (curChar == 115 && kind > 61)
                     kind = 61;
                  break;
               case 332:
                  if (curChar == 73)
                     jjAddStates(9, 10);
                  break;
               case 334:
                  if (curChar == 83 && kind > 61)
                     kind = 61;
                  break;
               case 335:
                  if (curChar == 110)
                     jjAddStates(7, 8);
                  break;
               case 336:
                  if (curChar == 116 && kind > 64)
                     kind = 64;
                  break;
               case 338:
                  if (curChar == 119 && kind > 79)
                     kind = 79;
                  break;
               case 339:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 340:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 339;
                  break;
               case 341:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 342:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 343:
                  if (curChar == 78)
                     jjAddStates(5, 6);
                  break;
               case 344:
                  if (curChar == 84 && kind > 64)
                     kind = 64;
                  break;
               case 345:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 346:
                  if (curChar == 87 && kind > 79)
                     kind = 79;
                  break;
               case 347:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 348:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 349:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 348;
                  break;
               case 350:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 364 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_2(0x20L);
      default :
         return 1;
   }
}
static private int jjMoveStringLiteralDfa1_2(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      default :
         return 2;
   }
   return 2;
}
static private int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(0, 0);
}
static private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 3;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                  }
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   352, 353, 354, 361, 362, 345, 350, 337, 342, 333, 334, 330, 331, 327, 328, 324, 
   325, 318, 320, 322, 312, 314, 316, 306, 310, 297, 301, 273, 276, 282, 287, 292, 
   256, 264, 270, 238, 246, 252, 218, 224, 229, 234, 207, 211, 214, 198, 202, 205, 
   182, 187, 191, 196, 165, 170, 174, 179, 151, 155, 158, 162, 136, 140, 143, 147, 
   114, 120, 126, 132, 94, 100, 106, 112, 76, 80, 83, 88, 92, 54, 58, 61, 
   66, 70, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\47", "\42", "\173", "\175", "\50", 
"\51", "\133", "\135", "\75", "\53", "\55", "\52", "\57", "\54", "\75\75", "\41\75", 
null, "\174", "\76", "\74", "\76\75", "\74\75", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, 
"\122\145\146\145\162\145\156\143\145", null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\72", "\72\72", null, null, null, null, null, null, "\101\162\162\141\171", 
"\124\141\142\154\145", "\111\156\164\145\147\145\162", "\104\157\165\142\154\145", 
"\102\157\157\154\145\141\156", "\123\164\162\151\156\147", "\104\141\164\145", 
"\123\164\157\143\153\123\171\155\142\157\154", "\104\141\164\141\111\156\163\164\141\156\143\145", "\123\150\141\160\145", 
"\105\170\164\145\156\163\151\157\156", "\121\165\145\162\171", null, null, null, null, null, 
"\156\145\167\114\151\156\145", null, null, null, null, "\73", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_SINGLE_LINE_COMMENT",
   "IN_MULTI_LINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, 1, 2, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0x3ffffffL, 
};
static final long[] jjtoSkip = {
   0x32L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x32L, 0x0L, 
};
static final long[] jjtoMore = {
   0x4cL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[364];
static private final int[] jjstateSet = new int[728];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public CALRuleParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public CALRuleParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 364; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 6)
         {
            jjmatchedKind = 6;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 6)
         {
            jjmatchedKind = 6;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
